version: "1"

services:
  postgres:
    image: postgres:alpine3.14
    container_name: database-postgres-parcial
    restart: always
    environment:
    - POSTGRES_PASSWORD=Unu#2025
    ports:
    - 5439:5432
    networks:
    - EP2025
    
networks:
  EP2025:
    name: ms-parcial-postgres

